# Generated by Django 3.0.8 on 2020-10-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='source_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='题目来源地址'),
        ),
    ]
