# Generated by Django 3.0.8 on 2020-09-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(max_length=50, verbose_name='来源')),
                ('account_id', models.TextField(max_length=30, verbose_name='账号')),
                ('account_password', models.TextField(max_length=30, verbose_name='密码')),
            ],
        ),
    ]
