# Generated by Django 3.0.8 on 2020-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=1, verbose_name='难度等级'),
            preserve_default=False,
        ),
    ]
