# Generated by Django 3.0.8 on 2020-11-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='类型')),
                ('vote_number', models.IntegerField(default=1, verbose_name='投票数')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
    ]
