# Generated by Django 3.0.8 on 2020-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200912_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='题目编号'),
        ),
    ]
