# Generated by Django 3.0.8 on 2020-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20200912_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
