# Generated by Django 3.0.8 on 2020-09-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20200912_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='memory_limit_C',
            new_name='memory_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='time_limit_C',
            new_name='time_limit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='memory_limit_other',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='time_limit_other',
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='problem_category', to='problems.Category', verbose_name='类型'),
        ),
    ]
