# Generated by Django 3.0.8 on 2020-09-14 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0006_auto_20200914_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.TimeField(auto_created=True, verbose_name='提交时间')),
                ('result', models.CharField(max_length=200, verbose_name='结果')),
                ('time', models.IntegerField(verbose_name='时间')),
                ('memory', models.IntegerField(verbose_name='内存')),
                ('code_length', models.IntegerField(verbose_name='代码长度')),
                ('lang', models.CharField(max_length=200, verbose_name='语言')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_status', to='problems.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
