# Generated by Django 3.0.8 on 2020-10-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.TextField(default='', verbose_name='提交代码'),
        ),
    ]
