# Generated by Django 3.0.8 on 2020-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_status_is_first_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_first_submit',
            field=models.BooleanField(default=False, verbose_name='是否是第一次提交'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_first_ac',
            field=models.BooleanField(default=False, verbose_name='是否是第一次ac'),
        ),
    ]
